[pr_reviewer] # /review #
extra_instructions = """
Please describe the issue_content field in Chinese.
Please translate the string 'PR Reviewer Guide' into Chinese. 
"""
# review labels
enable_review_labels_security=false
enable_review_labels_effort=false

[pr_description] # /describe #
publish_labels = false
add_original_user_description = true
generate_ai_title = false
use_bullet_points = true
extra_instructions = "Please describe all the contents of the Description field in Chinese."
enable_pr_type = false

[pr_code_suggestions] # /improve #
extra_instructions = "Please describe all the contents of the Suggestions field in Chinese."
