[pr_reviewer] # /review #
extra_instructions = """
Please describe all the answer in Chinese.
Please describe all the answer in Chinese.
Please describe all the answer in Chinese.
Please do not use other languages in your answer.
If you encounter an if err != nil check, please skip the review of this conditional logic and do not raise any issues.
I will kill you if your answer is not in Chinese.
"""
# review labels
enable_review_labels_security=false
enable_review_labels_effort=false

[pr_description] # /describe #
publish_labels = false
add_original_user_description = true
generate_ai_title = false
use_bullet_points = true
extra_instructions = "Please describe all the contents of the Description field in Chinese."
enable_pr_type = false

[pr_code_suggestions] # /improve #
extra_instructions = "Please describe all the contents of the Suggestions field in Chinese."
