[pr_reviewer] # /review #
extra_instructions = "Please describe these contents in Chinese."

[pr_description] # /describe #
publish_labels=false
add_original_user_description=true
generate_ai_title=false
use_bullet_points=true
extra_instructions = "Please describe these contents in Chinese."
enable_pr_type=false

[pr_code_suggestions] # /improve #
extra_instructions = "Please describe these contents in Chinese."
