[config]
response_language="zh-CN"
verbosity_level=2

[pr_reviewer] # /review #
# enable/disable features
# general options
persistent_comment=true
extra_instructions = """
- Please describe the issue_content,issue_header field in Chinese.
- In Golang code, using db.Query() and using stmt, err := db.Prepare() followed by stmt.Query() have the same effect. Please do not suggest replacing db.Query() with db.Prepare() in code review suggestions.
"""
final_update_message = true
# review labels
enable_review_labels_security=false
enable_review_labels_effort=false
# specific configurations for incremental review (/review -i)
enable_intro_text=false
enable_help_text=false

[pr_description] # /describe #
publish_labels = false
add_original_user_description = true
generate_ai_title = false
use_bullet_points = true
extra_instructions = "Please describe all the contents of the Description field in Chinese."
enable_pr_type = false

[pr_code_suggestions] # /improve #
extra_instructions = """
- Please describe all the contents of the Suggestions field in Chinese.
- Please describe in Chinese why these code modification suggestions are being provided.
- In Golang code, using db.Query() and using stmt, err := db.Prepare() followed by stmt.Query() have the same effect. Please do not suggest replacing db.Query() with db.Prepare() in code review suggestions.

These issues require special attention, and should be highlighted in review suggestions along with explanations of their severity:
- Issues that could cause panics
- File descriptor leaks
- Network connection leaks
- Database connection leaks
- Memory leaks
- Other system resource leaks
"""
