name: prevent-file-change
on:
  pull_request:
    branches:
      - '*-ee'
jobs:
  prevent-file-change:
    if: github.head_ref != 'main' && !startsWith(github.head_ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: xalvarez/prevent-file-change-action@68cb9ec1e79b5acdba73eecc2acb92ce9cb4c83c
        name: Prevent file change
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: ^(?!.*_ee\.go$)(?!.*_ee_test\.go$)(?!.*_rel\.go$)(?!.*_rel_test\.go$)(?!go\.mod$)(?!go\.sum$)(?!\.github\/workflows\/check-pr-files\.yml$)(?!vendor\/.*).*
          trustedAuthors: xalvarez