name: prevent-file-change
on:
  pull_request:
    types:
      - opened
    branches:
      - '*-ee'
jobs:
  check-bats-version:
    if: github.ref != 'refs/heads/*-ee'
    runs-on: ubuntu-latest
    steps:
      - uses: xalvarez/prevent-file-change-action@v1
        name: Prevent file change
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: ^(?!.*-ee\.go$).*
          trustedAuthors: xalvarez